### ISSUE TITLE
No Map Showing

### ISSUE THREAD

**Issue by tanz-tilsontech** [spatialnetworks/share-maps#2]
I would like to use this, but there is no map that pulls up. Can this be fixed?

**Comment by bmcbride** [comment]
Closed by 86c6faf. FYI: @tanz-tilsontech this repo is no longer actively maintained. It still seems to be working, but I'd recommend switching over to https://github.com/mapzap/mapzap.github.io, which is less Fulcrum specific and more actively maintained.

**Comment by tanz-tilsontech** [comment]
I see you changed out the map and now it works. I’ve checked on the mapzap and really don’t like the layout and mine is for Fulcrum Specific. I like that yours allows to download all the files and the Search is on the left pane.

One thing though, would you be capable of adding Satellite map and the ability to select the status to filter from in the Legend?

I won’t ask you for anything else and consider this IO closed.

Thanks,

[Company logo Invisible Background]
Tanner Anz | Senior Project Coordinator
385 W 2880 S, South Salt Lake, UT 84115
m: +1 801-989-8726 | f: +1 207-772-3427
tanz@tilsontech.com<mailto:tanz@tilsontech.com> | www.tilsontech.com<http://www.tilsontech.com/>
www.facebook.com/tilsontech<http://www.facebook.com/tilsontech>
www.linkedin.com/company/tilson-technology-management<http://www.linkedin.com/company/tilson-technology-management>
Utah General Engineering Contractor: 10425708-5551
